### ISSUE TITLE
Support for Windows aarch64?

### ISSUE THREAD

**Issue by yesudeep** [sgammon/rules_graalvm#146]
Hello, 

I'm wondering whether support for aarch64 Windows builds can be added?

```
pwsh❯ bazel build ...
INFO: Repository rules_graalvm~override~graalvm~graalvm instantiated at:
  callstack not available
Repository rule _graalvm_bindist_repository defined at:
  C:/users/yesudeep/_bazel_yesudeep/dtybepaq/external/rules_graalvm~override/internal/graalvm_bindist.bzl:561:46: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_graalvm~override~graalvm~graalvm':
   Traceback (most recent call last):
        File "C:/users/yesudeep/_bazel_yesudeep/dtybepaq/external/rules_graalvm~override/internal/graalvm_bindist.bzl", line 326, column 21, in _graal_bindist_repository_impl
                fail("Platform %s not supported at GraalVM version '%s' (distribution '%s'). Available: %s." % (
Error in fail: Platform windows-aarch64 not supported at GraalVM version '20.0.2' (distribution 'oracle'). Available: macos-x64, macos-aarch64, linux-x64, linux-aarch64, windows-x64.
ERROR: <builtin>: fetching _graalvm_bindist_repository rule //:rules_graalvm~override~graalvm~graalvm: Traceback (most recent call last):
        File "C:/users/yesudeep/_bazel_yesudeep/dtybepaq/external/rules_graalvm~override/internal/graalvm_bindist.bzl", line 326, column 21, in _graal_bindist_repository_impl
                fail("Platform %s not supported at GraalVM version '%s' (distribution '%s'). Available: %s." % (
Error in fail: Platform windows-aarch64 not supported at GraalVM version '20.0.2' (distribution 'oracle'). Available: macos-x64, macos-aarch64, linux-x64, linux-aarch64, windows-x64.
ERROR: Analysis of target '//lab/basic/cc:math_test' failed; build aborted: Platform windows-aarch64 not supported at GraalVM version '20.0.2' (distribution 'oracle'). Available: macos-x64, macos-aarch64, linux-x64, linux-aarch64, windows-x64.
INFO: Elapsed time: 0.426s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 22 targets configured)
    currently loading: @protobuf~21.7// ... (13 packages)
    Fetching repository @local_jdk; starting
    Fetching repository @rules_java~6.4.0~toolchains~local_jdk; starting

```

**Comment by sgammon** [comment]
Hello @yesudeep, thank you for your interest in this project and for filing this bug

Please see the error message provided:
```
ERROR: Analysis of target '//lab/basic/cc:math_test' failed; build aborted: Platform windows-aarch64 not supported at GraalVM version '20.0.2' (distribution 'oracle'). Available: macos-x64, macos-aarch64, linux-x64, linux-aarch64, windows-x64.
```

For GraalVM version `20.0.2` (previous latest), there is no `windows-aarch64` copy, only `windows-x64`. I am happy to ship an update here once GraalVM adds support

You may want to file a bug on the [Graal repo](https://github.com/oracle/graal) to get their attention
